<?php
/**
 * File: Randomizer.php
 * Project: GamerHelpDesk
 * Created Date: March 2026
 * Author: danutz0501 (M. Dumitru Daniel)
 * -----
 * Last Modified:
 * Modified By:
 * -----
 * Copyright (c) 2026 M. Dumitru Daniel (M. Dumitru Daniel)
 *  This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
declare(strict_types=1);

namespace GamerHelpDesk\Util\Randomizer;

use Random\Randomizer as BaseRandomizer;
use Random\Engine\{
    Mt19937,
    PcgOneseq128XslRr64,
    Xoshiro256StarStar,
    Secure
};

use GamerHelpDesk\Exception\{
    GamerHelpDeskException,
    GamerHelpDeskExceptionEnum
};

/**
 * Simple wrapper class for the Randomizer library.
 * @package GamerHelpDesk\Util\Randomizer   
 * @version 1.0.0
 */
class Randomizer
{
    /** @var BaseRandomizer */
    protected BaseRandomizer $randomizer;

    /**
     * Engine constants
     * @var string
     */
    public const ENGINE_MT19937 = 'Mt19937';
    public const ENGINE_PCG_ONESEQ128XSLRR64 = 'PcgOneseq128XslRr64';
    public const ENGINE_XOSHIRO256STARSTAR = 'Xoshiro256StarStar';
    public const ENGINE_SECURE = 'Secure';
  
    /**
     * Initializes a new instance of the Randomizer class.
     * @param string $engine The type of random number generator to use. Defaults to self::ENGINE_MT19937.
     * @throws GamerHelpDeskException If the specified engine is invalid.
     */
    public function __construct(string $engine = self::ENGINE_MT19937)
    {
        $this->randomizer = new BaseRandomizer(match ($engine) {
            self::ENGINE_MT19937 => new Mt19937(),
            self::ENGINE_PCG_ONESEQ128XSLRR64 => new PcgOneseq128XslRr64(),
            self::ENGINE_XOSHIRO256STARSTAR => new Xoshiro256StarStar(),
            self::ENGINE_SECURE => new Secure(),
            default => throw new GamerHelpDeskException(GamerHelpDeskExceptionEnum::INVALID_ARGUMENT_EXCEPTION, "Invalid engine specified")
        });
    }

    /**
     * Generates a random integer within the specified range.
     * @param int $min The minimum value (inclusive) of the range.
     * @param int $max The maximum value (inclusive) of the range.
     * @return int A random integer within the range.
     */
    public function generateInt(int $min, int $max): int
    {
        return $this->randomizer->getInt(min: $min, max: $max);
    }

    /**
     * Generates a random floating-point number within the specified range.
     * @param float $min The minimum value (inclusive) of the range.
     * @param float $max The maximum value (inclusive) of the range.
     * @return float A random floating-point number within the range.
     */
    public function generateFloat(float $min, float $max): float
    {
        return $this->randomizer->getFloat(min: $min, max: $max);
    }

    /**
     * Generates a random string of hexadecimal characters of the specified length.
     * The string is generated by converting a random byte sequence into hexadecimal form.
     * @param int $length The length of the string to generate.
     * @return string A random string of hexadecimal characters of the specified length.
     */
    public function generateString(int $length): string
    {
        return bin2hex($this->randomizer->getBytes(length: $length));
    }

    /**
     * Generates a random byte sequence of the specified length.
     * @param int $length The length of the byte sequence to generate.
     * @return string A random byte sequence of the specified length.
     */
    public function generateBytes(int $length): mixed
    {
        return $this->randomizer->getBytes(length: $length);
    }

    /**
     * Generates a random byte sequence of the specified length based on the provided string.
     * The string is used as a seed for the random number generator.
     * @param string $string The string to use as a seed for the random number generator.
     * @param int $length The length of the byte sequence to generate.
     * @return string A random byte sequence of the specified length based on the provided string.
     */
    public function getBytesForString(string $string, int $length): string
    {
        return $this->randomizer->getBytesFromString(string: $string, length: $length);
    }

    /**
     * Returns an array of randomly picked keys from the provided array.
     * The size of the returned array is equal to the specified number.
     * @param array $array The array to pick keys from.
     * @param int $num The number of keys to pick.
     * @return array An array of randomly picked keys from the provided array.
     */
    public function pickArrayKeys(array $array, int $num): array
    {
        return $this->randomizer->pickArrayKeys(array: $array, num: $num);
    }

    /**
     * Returns an array of randomly picked values from the provided array.
     * The size of the returned array is equal to the specified number.
     * @param array $array The array to pick values from.
     * @param int $num The number of values to pick.
     * @return array An array of randomly picked values from the provided array.
     */
    public function pickArrayValues(array $array, int $num): array
    {
        return array_map(static fn ($key) => $array[$key], $this->randomizer->pickArrayKeys(array: array_keys($array), num: $num));
    }

    /**
     * Shuffles the elements of the provided array.
     * @param array $array The array to shuffle.
     * @return array The shuffled array.
     */
    public function shuffleArray(array $array): array
    {
        return $this->randomizer->shuffleArray(array: $array);
    }

    /**
     * Shuffles the bytes of the provided string.
     * @param string $bytes The string to shuffle.
     * @return string The shuffled string.
     */
    public function shuffleBytes(string $bytes): string
    {
        return $this->randomizer->shuffleBytes(bytes: $bytes);
    }
}